id: PF8888455
initial_creation_type: ocr
source_metadata:
  volumes:
    42054ee2d7ab4215b38153657d38481d:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་དོན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1539
      volume_number: 1
